# Generated by Django 2.2 on 2019-11-05 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191105_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 8, 15, 39, 4436, tzinfo=utc)),
        ),
    ]
