# Generated by Django 2.2 on 2019-11-05 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191105_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 13, 44, 13, 978626, tzinfo=utc)),
        ),
    ]
